/* eslint-disable */
import { Environment } from '@app-environments/ienvironment.js';
import gulp from 'gulp';
import gulpLoadPlugins from 'gulp-load-plugins';
import fs from 'fs';
import path from 'path';
import del from 'del';
import { argv } from 'yargs';
import { getEnvironment } from './environment.task.js';
import { createHashes } from '../utils/hashes.js';
import { createSvgs } from '../utils/svgs.js';
import concat from 'gulp-concat';
import download from 'gulp-download';

const $ = <any>gulpLoadPlugins({ camelize: true });
const IS_MOBILE = argv['mobile'] || false;
const SUBDOMAIN = argv['subDomain'] || false;

let environment;
let fileHashes;
let svgs;
let siteConfig;

/**
 * return the appId from the mobile stores
 * @param storeName
 */
const getAppStoreId = (environment: Environment, storeName: 'ios' | 'android') => {
  const result = environment.settings.appStoreUrls.find((store) => store.name === storeName);

  if (!result || !result.appId) {
    return;
  }

  return result.appId;
};

/**
 * return domain of a url
 */
const getDomainFromUrl = (url: string): string | undefined => {
  if (!url) {
    return;
  }

  const regex = /(?:https?:\/\/)?(?:[^@\/\n]+@)?(?:www\.)?([^:\/\n]+)/i;
  const result = regex.exec(url);
  if (result !== null) {
    return result[0];
  }
  return;
};

/**
 * copy file and replace handlebar variables
 */
const handleBarGulpTask = (src, dest, config = siteConfig) => {
  return gulp.src(src).pipe($.compileHandlebars(config, handleBarSettings)).pipe(gulp.dest(dest));
};

/** minify file */
const minifyFileGulpTask = (src, dest, env = environment) => {
  env = env ? env : environment;
  const minifyEnabled = env.settings.environment !== 'dev';

  return gulp
    .src(src)
    .pipe(
      $.htmlmin({
        removeComments: minifyEnabled,
        collapseWhitespace: minifyEnabled,
        minifyJS: minifyEnabled,
        minifyCSS: minifyEnabled,
      }),
    )
    .pipe(gulp.dest(dest));
};

// general handlebar settings and helpers
const handleBarSettings = {
  compile: { noEscape: true },
  helpers: {
    cdn: (file) => {
      let filePathNew = file;

      // hash
      if (environment.settings.environment !== 'local') {
        const currentFile = fileHashes['hashes'].find((item) => item['path'] === file);

        if (currentFile) {
          filePathNew = currentFile.hashPath;
        }
      }

      // cdn
      if (environment.cdn.baseApiUrl !== '' && IS_MOBILE === 'false') {
        filePathNew = `${environment.cdn.baseApiUrl}${filePathNew}`;
      }

      return filePathNew;
    },
  },
};

/**
 * clean the src folder from the files which are generated by these site tasks
 */
gulp.task('site.cleanup', () => {
  return del([
    'src/app/site/index.ts',
    'src/debug-hashes.json',
    'src/hashes.json',
    'src/index.html',
    'src/styles/site.scss',
    'src/assets/svgs.json',
    'src/manifest.json',
    'src/assets/webpush/dist/**',
    '!src/assets/webpush/dist/',
  ]);
});

/**
 * Generate the environment an any other information for running the rest of the scripts
 */
gulp.task('site.preScripts', (done: any) => {
  environment = getEnvironment();
  done();
});

/**
 * update the configuration variables which are needed to generate the files
 */
export const handleBarConfigForIndexHtml = (environment: Environment, IS_MOBILE: unknown, IS_FUSION: boolean) => {
  return {
    // env
    environment: environment.settings.environment,
    // version
    version: environment.settings.version,
    timeStamp: new Date().toUTCString(),
    // mobile app
    isMobile: IS_MOBILE === 'true',
    isWeb: IS_MOBILE === 'false',
    isNoFusionEnvironment: !IS_FUSION,
    isProduction: environment.settings.environment === 'prod',
    // urls
    baseUrl: environment.settings.baseUrl,
    cdnUrl: getDomainFromUrl(environment.mba.cdnBaseApiUrl),
    mbaUrl: getDomainFromUrl(environment.mba.baseApiUrl),
    crmUrl: getDomainFromUrl(environment.crm.baseApiUrl),
    // meta
    name: environment.settings.name,
    nameShort: environment.settings.nameShort,
    nameInternal: environment.settings.nameInternal,
    title: environment.settings.title,
    description: environment.settings.description,
    languages: environment.settings.supportedLng,
    defaultLng: IS_MOBILE === 'true' ? environment.settings.supportedLng[0] : '${lang}', // IMPORTANT: ${lang} is render in the webserver on the fly
    iosAppId: ['svch', 'adch', 'lslu'].includes(environment.settings.nameInternal) ? undefined : getAppStoreId(environment, 'ios'), // WHT-4730 temporary hack while we dont have the native apps.
    // optimizely
    optimizelyEnabled: IS_MOBILE === 'true' ? false : environment.features.optimizely,
    optimizelyUrl: environment.settings.optimizelyUrl,
    // oracleInfinity
    oracleInfinityEnabled: environment.features.oracleInfinity,
    oracleInfinityUrl: environment.settings.oracleInfinityUrl,
    // google tag manager
    gtmEnabled: environment.settings.environment !== 'dev',
    // only if we mobile apps we set the ios for now as web/android is the same
    gtmId: IS_MOBILE === 'true' ? '' : environment.analytics.web,
    // pwa
    pwaBannerDescription: environment.pwa.bannerDescription,
    pwaEnabled: environment.pwa.$enabled,
    pwaHideInstallBanner: !(environment.pwa.$enabled && environment.pwa.showInstallBanner),
    // xtremepush account
    xtremePushID: environment.xtremePush.gcmSenderID,
    xtremepushAppKey: environment.xtremePush.appKey,
    // kambi
    kambiSportsFeedWidgetJS: environment.sports.feedWidget.bundleJS,
    kambiSportsFeedWidget: environment.features.kambiSportsFeedWidget,
    // styles
    backgroundColor: environment.settings.styles.backgroundColor,
    maskIconColor: environment.settings.styles.maskIconColor,
    themeColor: environment.settings.styles.themeColor,
    cdnWebAssetsFullUrl: environment.cdn.baseApiUrl,
    cdnGameAssetsFullUrl: environment.mba.cdnBaseApiUrl,
    mbaFullUrl: environment.mba.baseApiUrl,
    payseraVerificationMeta: environment.settings.payseraVerificationMeta,
    seonUrl: environment?.seon?.sourceUrl,
  };
};
gulp.task('site.config.generate', (done: any) => {
  siteConfig = handleBarConfigForIndexHtml(environment, IS_MOBILE, !!SUBDOMAIN);
  done();
});

/**
 * generate hashes for the given files
 */
gulp.task('site.hashes.create', (done: any) => {
  fileHashes = createHashes({
    src: 'src/',
    glob: [
      'src/assets/browser-update/*',
      'src/assets/deposit-widget/deposit.min.css',
      'src/assets/fonts/**/*.{woff,woff2}',
      // ... rest of glob patterns
    ],
    ignore: [
      // ... ignore patterns
    ],
    parameterHash: ['src/manifest.json'],
  });

  done();
});

/**
 * generate a json file which contains the file hashes from all files in the src folder
 */
gulp.task('site.hashes.saveJsonFile', (done: any) => {
  // debug generated hashes
  // fs.writeFileSync('src/debug-hashes.json', JSON.stringify(fileHashes, null, 2));

  fs.writeFileSync(
    'src/hashes.json',
    (() => {
      if (environment.settings.environment === 'local') {
        return '{}';
      }
      const json = {};
      fileHashes.hashes.forEach((currentFile) => {
        json[currentFile.path] = currentFile.hash;
      });
      return `${JSON.stringify(json, null, 2)}\n`;
    })(),
  );

  done();
});

/**
 * rename all files in the hash folder and add hash to their path
 */
gulp.task('site.hashes.rename', (done: any) => {
  if (environment.settings.environment !== 'local') {
    fileHashes.hashes.forEach((currentFile) => {
      if (currentFile.rename) {
        fs.renameSync(path.join(fileHashes.assetFolder, currentFile.path), path.join(fileHashes.assetFolder, currentFile.hashPath));
      }
    });
  }

  done();
});

/**
 * generate a json file which contains information about svgs
 */
gulp.task('site.svgs', (done: any) => {
  svgs = createSvgs({
    // sprites: [
    //   'src/assets/img/sprites/*/*.svg'
    // ],
    inline: [
      'src/assets/img/icons/*.svg',
      'src/assets/img/payments/*.svg',
      'src/assets/img/social/*.svg',
      'src/assets/img/usps/*.svg',
      'src/assets/img/playsafe/*.svg',
      'src/assets/img/fast-withdrawals/*.svg',
    ],
  });

  fs.writeFileSync('src/assets/svgs.json', `${JSON.stringify(svgs, null, 2)}\n`);

  done();
});

/**
 * copy files
 */
gulp.task('site.font.face', () => handleBarGulpTask('src/assets/fonts/font-face.html', 'src/assets/fonts'));
gulp.task('site.font.preload', () => handleBarGulpTask('src/assets/fonts/font-preload.html', 'src/assets/fonts'));
gulp.task('site.index.ts', () => handleBarGulpTask('sites/core/src/app/site/index.ts', 'src/app/site'));
gulp.task('site.app.config.ts', () => handleBarGulpTask(`sites/${environment.settings.nameInternal}/src/app/app.config.ts`, 'src/app/main'));
gulp.task('site.regulatorConfig.ts', () =>
  handleBarGulpTask('sites/core/src/app/api/aggregator/regulatorConfig.ts', 'src/app/api/aggregator', { regulatorProvider: environment.settings.regulatorProvider }),
);
gulp.task('site.deposit.html', () => handleBarGulpTask('sites/core/src/assets/deposit-widget/deposit.html', 'src/assets/deposit-widget'));
gulp.task('site.manifest.json', () => handleBarGulpTask('sites/core/src/manifest.json', 'src'));
gulp.task('site.service-worker.js', () => handleBarGulpTask('sites/core/src/service-worker.js', 'src'));

// xtremepush service worker
gulp.task('site.xtremepush-service-worker.js', (done: any) => {
  return download(`https://prod.webpu.sh/${siteConfig.xtremepushAppKey}/service-worker-source.js`)
    .pipe(gulp.src('sites/core/src/service-worker.js'))
    .pipe(concat('service-worker.js'))
    .pipe($.compileHandlebars(siteConfig, handleBarSettings))
    .pipe(gulp.dest('src'))
    .on('end', done);
});

// index html
gulp.task('site.index.html', () => {
  const config = Object.assign(siteConfig, {
    fileFontFaceDefinition: fs.readFileSync('src/assets/fonts/font-face.html', 'utf8'),
    fileFontPreloadMetaInformation: fs.readFileSync('src/assets/fonts/font-preload.html', 'utf8'),
    fileLoadingScreen: fs.readFileSync('src/assets/img/logos/main-logo-loading-screen.html', 'utf8'),
  });
  return handleBarGulpTask('sites/core/src/index.html', 'src', config);
});

/**
 * Copy mobile plugin files
 * web: mock plugins
 * app: ionic plugins
 */
gulp.task('site.mobile.plugins.index.ts', (done: any) => {
  let src = '';
  if (IS_MOBILE === 'true') {
    src = `sites/core/src/app/core/mobile/index.mobile.ts`;
  } else {
    src = `sites/core/src/app/core/mobile/index.ts`;
  }

  return gulp.src(src).pipe($.rename('index.ts')).pipe(gulp.dest('src/app/core/mobile'));
});

/**
 * minify files
 */
gulp.task('site.minify.deposit.html', () => minifyFileGulpTask('src/assets/deposit-widget/deposit.html', 'src/assets/deposit-widget'));
gulp.task('site.minify.index.html', () => minifyFileGulpTask('src/index.html', 'src'));

/**
 * generate a sass file which contains settings needed in scss
 */
gulp.task('site.scss', (done: any) => {
  fs.writeFileSync(
    'src/styles/site.scss',
    (() => {
      let value = '';

      value += `@import '${environment.settings.nameInternal}/setup';\n\n`;
      value += `$site: (\n`;
      value += `  'site': '${environment.settings.nameInternal}',\n`;
      value += `  'env': '${environment.settings.environment}',\n`;
      value += `);\n`;

      return value;
    })(),
  );

  done();
});

/**
 * build site
 */
export const buildSite = gulp.series(
  'site.cleanup',
  'site.preScripts',
  'site.config.generate',
  'site.hashes.create',
  gulp.parallel(
    'site.font.face',
    'site.font.preload',
    'site.index.ts',
    'site.app.config.ts',
    'site.regulatorConfig.ts',
    'site.deposit.html',
    'site.manifest.json',
    'site.mobile.plugins.index.ts',
    'site.service-worker.js',
    'site.xtremepush-service-worker.js',
  ),
  'site.hashes.create',
  gulp.parallel('site.index.html'),
  // gulp.parallel('site.minify.deposit.html', 'site.minify.index.html'),
  'site.svgs',
  'site.hashes.create',
  'site.scss',
  'site.hashes.saveJsonFile',
  'site.hashes.rename',
);

export { handleBarSettings, minifyFileGulpTask };
